services:
  pz-proxy:
    image: traefik:v3.0
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml
      
    labels:
      - "traefik.enable=true"
    depends_on:
      pz-api:
      pz-db:
        condition: service_healthy
  
  pz-api:
    image: massand3r/parteez-api:latest
    ports:
      - 8080:8080
    depends_on:
      pz-db:
        condition: service_healthy

  pz-db:
    image: postgres:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Uncomment to expose ports
    ports:
      - 5432:5432
    volumes:
      - ./docker/data/pz-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  pz-db-data:
    driver: local

secrets:
  cf_api_token:
    file: ./cf_api_token.txt
